spring.application.name=licoreria

spring.datasource.url=jdbc:postgresql://localhost:5432/licoreria_db
spring.datasource.username=licoreria_user
spring.datasource.password=licoreria_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

app.jwt.secret=mi-clave-secreta-para-desarrollo-de-licoreria-2026
app.jwt.expiration=86400000